@startuml WarmHouse_component_door

title Door service component

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(WarmHouseSystem, "WarmHouse system") {
    Container(WebApp, "Web application", "Go", "Handles user interactions")
    Container(DoorService, "Door service", "Go", "Interact with doors")
}

Container(DoorService, "Door service", "Go") {
    Component(FrontMaker, "FrontendMaker", "Generate microfrontend")
    Component(DeviceController, "DeviceController", "Communicates with device")
    Component(ScheduleController, "ScheduleController", "Execute user's program")
}

Rel(WebApp, FrontMaker, "Call buisness logic")
Rel(FrontMaker, DeviceController, "Read/write data")
Rel(FrontMaker, ScheduleController, "Configure schedule")
Rel(ScheduleController, DeviceController, "Send commands")

@enduml